# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shop?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: zrq66689
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        servlet:
            content-type: text/html
        mode: HTML
    mvc:
        static-path-pattern: /static/**
    jpa:
        hibernate:
            #自动更新
            ddl-auto: update
        #日志显示sql语句
        show-sql: true
server:
    port: 8183

